#!/bin/bash
# InvestWithDiomin.today - Production Deployment Commands
# Run these commands in your terminal to go LIVE

echo "🚀 InvestWithDiomin.today Deployment Script"
echo "=============================================="
echo ""

# Step 1: Install Vercel CLI
echo "Step 1: Installing Vercel CLI..."
echo "Command: npm install -g vercel"
echo ""
echo "Run this in your terminal:"
echo "  npm install -g vercel"
echo ""
echo "---"
echo ""

# Step 2: Login to Vercel
echo "Step 2: Login to Vercel..."
echo "Command: vercel login"
echo ""
echo "Run this in your terminal:"
echo "  vercel login"
echo ""
echo "This will open your browser to authenticate. Follow the prompts."
echo ""
echo "---"
echo ""

# Step 3: Deploy to Production
echo "Step 3: Deploy to Production..."
echo "Command: vercel --prod"
echo ""
echo "Run this in your terminal:"
echo "  vercel --prod"
echo ""
echo "Wait for completion. You'll see:"
echo "  ✔ Production deployment complete"
echo "  ✔ Deployed URL: https://investwithdiomin-XXXXX.vercel.app"
echo ""
echo "---"
echo ""

# Step 4: Add Environment Variables
echo "Step 4: Add Environment Variables to Vercel"
echo ""
echo "Go to: https://vercel.com/dashboard"
echo "1. Select your InvestWithDiomin project"
echo "2. Click Settings → Environment Variables"
echo "3. Add these 6 variables (copy values from your .env file):"
echo ""
echo "  VITE_SUPABASE_URL"
echo "  VITE_SUPABASE_ANON_KEY"
echo "  VITE_MAILCHIMP_SERVER"
echo "  VITE_MAILCHIMP_AUDIENCE_ID"
echo "  VITE_MAILCHIMP_API_KEY"
echo "  VITE_OPENAI_API_KEY"
echo ""
echo "4. Click Save after each variable"
echo ""
echo "---"
echo ""

# Step 5: Redeploy with environment variables
echo "Step 5: Redeploy with Environment Variables"
echo "Command: vercel --prod"
echo ""
echo "Run this in your terminal again:"
echo "  vercel --prod"
echo ""
echo "This redeployment includes your environment variables."
echo ""
echo "---"
echo ""

# Step 6: Connect your domain
echo "Step 6: Connect Your Domain"
echo "Command: vercel domains add investwithdiomin.today"
echo ""
echo "Run this in your terminal:"
echo "  vercel domains add investwithdiomin.today"
echo ""
echo "Vercel will show you 3 options. Choose ONE:"
echo ""
echo "  Option A: Use Vercel Nameservers (EASIEST)"
echo "    - Go to your domain registrar (GoDaddy, Namecheap, etc.)"
echo "    - DNS settings"
echo "    - Change nameservers to:"
echo "      ns1.vercel-dns.com"
echo "      ns2.vercel-dns.com"
echo ""
echo "  Option B: Add A Record"
echo "    - Go to your domain registrar"
echo "    - DNS settings"
echo "    - Add A record: 76.76.21.21"
echo ""
echo "  Option C: Add CNAME"
echo "    - Go to your domain registrar"
echo "    - DNS settings"
echo "    - www CNAME → cname.vercel-dns.com"
echo ""
echo "Choose one and save."
echo ""
echo "---"
echo ""

# Step 7: Setup email
echo "Step 7: Setup Email (book@investwithdiomin.today)"
echo ""
echo "Go to your domain registrar email settings:"
echo ""
echo "Option A: Email Forwarding (FREE)"
echo "  Create forwarding rule:"
echo "    book@investwithdiomin.today → your-personal-email@gmail.com"
echo ""
echo "Option B: Full Email Hosting (PROFESSIONAL)"
echo "  Sign up with: Zoho Mail ($2-7/mo) or Gmail Business ($6/mo)"
echo "  Configure MX records"
echo "  Wait 24 hours"
echo ""
echo "---"
echo ""

# Step 8: Wait for DNS
echo "Step 8: Wait for DNS Propagation (24-48 hours)"
echo ""
echo "DNS propagates automatically. Check status:"
echo "  https://www.whatsmydns.net"
echo ""
echo "When you see:"
echo "  investwithdiomin.today → 76.76.21.21 ✅"
echo "  HTTPS certificate → Active ✅"
echo ""
echo "---"
echo ""

# Step 9: Test
echo "Step 9: Test Your Live Site"
echo ""
echo "Visit: https://investwithdiomin.today"
echo ""
echo "Test these:"
echo "  ✅ Homepage loads"
echo "  ✅ Navigate to /about"
echo "  ✅ Newsletter signup works"
echo "  ✅ Consultation booking works"
echo "  ✅ Contact form submits"
echo "  ✅ Dark mode toggle works"
echo "  ✅ Mobile responsive"
echo ""
echo "---"
echo ""

# Step 10: Go Live
echo "Step 10: Go Live! 🎉"
echo ""
echo "Your site is now LIVE at:"
echo "  https://investwithdiomin.today"
echo "  Email: book@investwithdiomin.today"
echo ""
echo "Next steps:"
echo "  1. Announce on social media"
echo "  2. Send launch email"
echo "  3. Monitor admin dashboard"
echo "  4. Respond to leads"
echo "  5. Build your client base"
echo ""
echo "---"
echo ""

echo "🚀 DEPLOYMENT COMPLETE!"
echo ""
echo "Questions? See these files:"
echo "  - GO_LIVE_NOW.md (quick reference)"
echo "  - QUICK_START_DEPLOY.md (step-by-step)"
echo "  - VERCEL_DEPLOYMENT_SETUP.md (detailed guide)"
echo ""
echo "Good luck! 🎉"
